name: Sync Company Repos into Deep Paths

on:
  push:
    branches:
      - 'main/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git-filter-repo
        run: pip install git-filter-repo

      - name: Setup git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # proj_a → ./aaa/bbb/proj_a（扩展新项目：复制本段，改分支名 / tmp_x / 子目录）
      - name: Sync esp32s3_ws
        if: github.ref == 'refs/heads/main/esp32s3_ws'
        run: |
          git checkout main/esp32s3_ws
          git checkout -b tmp_esp32s3_ws
          git filter-repo --to-subdirectory-filter examples/idf/esp32s3/esp32s3_ws --force --refs refs/heads/tmp_esp32s3_ws
          git checkout main
          git merge tmp_esp32s3_ws --allow-unrelated-histories --no-edit

      - name: Sync esp32s3_rtc
        if: github.ref == 'refs/heads/main/esp32s3_rtc'
        run: |
          git checkout main/esp32s3_rtc
          git checkout -b tmp_esp32s3_rtc
          git filter-repo --to-subdirectory-filter examples/idf/esp32s3/esp32s3_rtc --force --refs refs/heads/tmp_esp32s3_rtc
          git checkout main
          git merge tmp_esp32s3_rtc --allow-unrelated-histories --no-edit

      - name: Push result
        run: git push origin main